language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run coverage
before_install:
    - npm install --save ysui@0.0.2 react@15.4.0 react-dom@15.4.0 react-router@3.0.2
after_script:
    - npm install coveralls && nyc report --reporter=text-lcov | coveralls
